# docker-compose up `service-name` to build

version: '2'

services:
  matrix-bot-uptimerobot:
    image: matrix-bot-uptimerobot:latest
    container_name: matrix-bot-uptimerobot
    ports:
      - 33001:33001